name=evar
version=1.0.0
author=Dmitry Dvoinikov
maintainer=Dmitry Dvoinikov <dmitry@targeted.org>
sentence=Cooperative task scheduler with message passing
paragraph=
category=Timing
url=https://github.com/targeted/evar
architectures=*